env:
  es6: true
  browser: true
  commonjs: true
  jest: true
   #Это необходимо, чтобы ESlint корректно проверял файлы с тестами.

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2017 #6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'
    #  Подробные сведения о каждом параметре конфигурации вы сможете получить на сайте ESLint.
